services:
  deployer:
    build: .
    image: ${APP_CONTAINER}
    container_name: ${APP_CONTAINER}-deployer
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - CHAIN_URL=${CHAIN_URL}
      - LOOP_BOUND=${LOOP_BOUND}
      - ENTRY_PER_TX=${ENTRY_PER_TX}
      - PRIVATE_KEYS=${PRIVATE_KEYS}
      - RECEIPT_INTERVAL=${RECEIPT_INTERVAL}
    entrypoint: '/app/deploy'

  pumper:
    build: .
    image: ${APP_CONTAINER}
    container_name: ${APP_CONTAINER}-pumper
    depends_on:
      - database
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - CHAIN_URL=${CHAIN_URL}
      - LOOP_BOUND=${LOOP_BOUND}
      - ENTRY_PER_TX=${ENTRY_PER_TX}
      - PRIVATE_KEYS=${PRIVATE_KEYS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_CONTAINER=${DB_CONTAINER}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - RECEIPT_INTERVAL=${RECEIPT_INTERVAL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_RECIPIENTS=${MAIL_RECIPIENTS}
    entrypoint: '/app/pumper'

  validator:
    build: .
    image: ${APP_CONTAINER}
    mem_limit: ${MEM_LIMIT}
    cpus: ${NO_OF_CPUS}
    depends_on:
      - database
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - CHAIN_URL=${CHAIN_URL}
      - LOOP_BOUND=${LOOP_BOUND}
      - ENTRY_PER_TX=${ENTRY_PER_TX}
      - PRIVATE_KEYS=${PRIVATE_KEYS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_CONTAINER=${DB_CONTAINER}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - RECEIPT_INTERVAL=${RECEIPT_INTERVAL}
    entrypoint: '/app/validator'

  api:
    build: .
    image: ${APP_CONTAINER}
    container_name: ${APP_CONTAINER}-api
    depends_on:
      - database
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - CHAIN_URL=${CHAIN_URL}
      - LOOP_BOUND=${LOOP_BOUND}
      - ENTRY_PER_TX=${ENTRY_PER_TX}
      - PRIVATE_KEYS=${PRIVATE_KEYS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_CONTAINER=${DB_CONTAINER}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - RECEIPT_INTERVAL=${RECEIPT_INTERVAL}
      - API_PORT=${API_PORT}
    entrypoint: '/app/server'
    ports:
      - ${API_PORT}:${API_PORT}

  database:
    image: postgres:latest
    container_name: ${DB_CONTAINER}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ${DB_VOLUME}
