[package]
name = "event-query"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0.25", features = ["full"] }
eyre = "0.6.12"
futures = "0.3"
tokio = { version = "1.47.1", features = ["full"] }
